---
#- name: install java

#- name: download tomcat zip
#  get_url:
#    url: "{{ tomcat_tar_url }}"
#    dest: "{{ root_dir }}/"

- name: remove tomcat directory if exists
  file:
    path: "{{ tomcat_dir }}"
    state: absent

- name: unarchive tomcat zip
  unarchive:
    src: "{{ root_dir }}/apache-tomcat-9.0.29.tar.gz"
    dest: "{{ root_dir }}/"

- name: change tomcat dir name
  command: mv "{{ root_dir }}/apache-tomcat-9.0.29/" "{{ tomcat_dir }}/"

- name: change tomcat port to 8090
  template:
    src: server.xml.j2
    dest: "{{ tomcat_dir }}/conf/server.xml"

- name: copy war source file to tomcat
  copy:
    src: "{{ source_war_path }}"
    dest: "{{ tomcat_dir }}/webapps/"

- name: start tomcat
  shell: chdir="{{ tomcat_dir }}/bin" nohup ./startup.sh start &